# Generated by Django 4.2.15 on 2024-10-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('country_city', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, default='blank.png', upload_to='trip')),
            ],
        ),
    ]
