# Generated by Django 4.2.15 on 2024-10-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
