# Generated by Django 4.2.15 on 2024-10-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_upcoming_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
