# Generated by Django 4.2.15 on 2024-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='price'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='random_images'),
        ),
    ]
