# Generated by Django 4.2.15 on 2024-10-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_price_image_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='price'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='random_images'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='profile_img',
            field=models.ImageField(default='blank.png', upload_to='trip'),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='img',
            field=models.ImageField(default='blank.png', upload_to='trip'),
        ),
    ]
