# Generated by Django 4.2.15 on 2024-10-13 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_price_image_alter_review_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itenerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(max_length=300)),
                ('lodging', models.CharField(max_length=300)),
                ('activities', models.CharField(max_length=300)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
